'use strict';
const key='jl-sat-profiles-v1',sections=['Desmos Mastery','Grammar Mastery','Non-Desmos','Reading Comprehension'];
let store={active:'default',profiles:{default:{name:'My practice',answers:{},watched:{}}}},storageOK=true;
try{const s=JSON.parse(localStorage.getItem(key));if(s&&s.profiles&&s.profiles[s.active])store=s}catch{}
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rich=s=>esc(s).replace(/&lt;u&gt;/g,'<u>').replace(/&lt;\/u&gt;/g,'</u>').replace(/&lt;sup&gt;/g,'<sup>').replace(/&lt;\/sup&gt;/g,'</sup>');
const profile=()=>store.profiles[store.active];
function save(){try{localStorage.setItem(key,JSON.stringify(store))}catch{storageOK=false;$('#profile-status').textContent='Browser storage is unavailable. Export a backup before leaving.'}}
// Reset snapshots live in this tab so Undo survives a reload without changing backups.
const resetUndoKey='jl-sat-reset-undo-v1';
let resetUndo={revision:0,revisions:{},actions:[]},resetMessage='';
try{const pending=JSON.parse(sessionStorage.getItem(resetUndoKey));if(pending&&Number.isSafeInteger(pending.revision)&&pending.revisions&&Array.isArray(pending.actions))resetUndo=pending}catch{}
const resetSlot=(profileId,questionId)=>JSON.stringify([profileId,questionId]);
function saveResetUndo(){try{sessionStorage.setItem(resetUndoKey,JSON.stringify(resetUndo))}catch{}}
function markAnswerChanged(profileId,questionId){const revision=++resetUndo.revision;resetUndo.revisions[resetSlot(profileId,questionId)]=revision;return revision}
function restorableEntries(action){const target=store.profiles[action.profileId];if(!target)return [];return action.entries.filter(entry=>resetUndo.revisions[resetSlot(action.profileId,entry.id)]===entry.revision&&!Object.prototype.hasOwnProperty.call(target.answers,entry.id))}
function pendingReset(){return resetUndo.actions.findLast(action=>action.profileId===store.active&&restorableEntries(action).length)}
function resetSavedAnswers(ids,label){
 const profileId=store.active,target=profile(),entries=[];
 ids.forEach(id=>{if(!Object.prototype.hasOwnProperty.call(target.answers,id))return;const record=JSON.parse(JSON.stringify(target.answers[id]));delete target.answers[id];entries.push({id,record,revision:markAnswerChanged(profileId,id)})});
 if(entries.length){resetUndo.actions.push({profileId,label,entries});resetUndo.actions=resetUndo.actions.filter(action=>restorableEntries(action).length).slice(-20);resetMessage='';save();saveResetUndo()}
 const y=scrollY;render();window.scrollTo(0,y);
}
function undoLastReset(){
 const action=pendingReset();if(!action)return;
 const entries=restorableEntries(action),target=store.profiles[action.profileId];
 entries.forEach(entry=>{target.answers[entry.id]=JSON.parse(JSON.stringify(entry.record));markAnswerChanged(action.profileId,entry.id)});
 resetUndo.actions=resetUndo.actions.filter(item=>item!==action&&restorableEntries(item).length);resetMessage=`${entries.length===1?'Question and its attempt history':entries.length+' questions and their attempt histories'} restored.`;save();saveResetUndo();const y=scrollY;render();window.scrollTo(0,y);
}
function resetStatusHTML(){const action=pendingReset();if(action){const count=restorableEntries(action).length;return `<aside class="reset-toast" role="status" aria-live="polite"><span>${count===1?'Question':count+' questions'} reset. ${count===1?'Its answer and attempt history were':'Their answers and attempt histories were'} cleared.</span><button data-undo-reset>Undo reset</button></aside>`}return resetMessage?`<aside class="reset-toast" role="status" aria-live="polite"><span>${esc(resetMessage)}</span><button data-dismiss-reset aria-label="Dismiss reset confirmation">Dismiss</button></aside>`:''}
function complete(l){return l.questions.every(q=>profile().answers[q.id]?.correct)}
function tally(l){return l.questions.filter(q=>profile().answers[q.id]?.correct).length}
function sectionLink(s){return 'sections.html#'+s}
function lessonLink(l){return '#lesson/'+l.id}
function courseNav(active=-1){return `<aside class="unit-nav"><a class="course-name" href="#course">James Lu SAT course<small>4 units · ${COURSE.lessons.length} lessons</small></a><nav aria-label="Course units">${sections.map((name,i)=>`<a href="#unit/${i}" ${i===active?'aria-current="page"':''}><span class="eyebrow">Unit ${i+1}</span><strong>${name}</strong></a>`).join('')}</nav><a href="#daily">Browse daily practice →</a></aside>`}
function lessonState(l){return complete(l)?'Complete':l.questions.some(q=>profile().answers[q.id])?'In progress':'Not started'}
const unitDescriptions=['Use Desmos for equations, systems, functions, inequalities, circles, and regression. Check the constraints and the exact quantity requested.','Identify clauses, choose punctuation, and handle verbs and sentence patterns. Apply each rule to a complete sentence.','Work through data analysis, probability, geometry, and trigonometry using mathematical reasoning.','Build evidence-based reading, inference, and transition skills. Support each choice with the exact relationship in the text.'];
function render(){
 $('#profile-button').textContent=profile().name;
 const route=location.hash.slice(1)||'home';let html='';
 if(route==='home'){
 const done=COURSE.lessons.filter(complete).length;
 const next=COURSE.lessons.find(l=>!complete(l))||COURSE.lessons[0];
 html=`<section class="hero"><div><div class="eyebrow">Independent course companion</div><h1 class="home-title">James Lu<br> SAT Practice</h1><p>Watch the lesson. Apply the method. Review the reasoning. Your videos and practice now follow one course, from Desmos to reading.</p><a class="action primary" href="${lessonLink(next)}">${done?'Continue':'Start'}: ${esc(next.title)} →</a><p class="hero-caption">${COURSE.lessons.length} lessons · ${COURSE.lessons.reduce((n,l)=>n+l.questions.length,0)} original questions · 4 section tests</p></div><aside class="course-map" aria-label="Your course progress"><div class="eyebrow">Your course, at a glance</div>`;
 sections.forEach((name,i)=>{const ls=COURSE.lessons.filter(l=>l.section===i);const n=ls.filter(complete).length;html+=`<a class="map-row" href="#unit/${i}"><span class="map-number">0${i+1}</span><div><strong>${name}</strong><div class="muted">${n} of ${ls.length} practice sets mastered</div><div class="progress"><div style="width:${n/ls.length*100}%"></div></div></div><span aria-hidden="true">↗</span></a>`});
 html+=`</aside></section><section class="practice-paths"><div><div class="eyebrow">Choose how to study</div><h2>A full course, or a focused session.</h2><p class="muted">Follow the lessons in order, choose a day to revisit, or put a whole section to the test.</p></div><div class="path-list"><a class="path-row" href="#course"><div><strong>Follow the course</strong><p>Video → lesson practice → section test</p></div><span aria-hidden="true">→</span></a><a class="path-row" href="#daily"><div><strong>Choose daily practice</strong><p>${COURSE.days.length} day and standalone sets, with answers and explanations</p></div><span aria-hidden="true">→</span></a><a class="path-row" href="sections.html"><div><strong>Take a section test</strong><p>112 bank questions; active questions excluded during selection</p></div><span aria-hidden="true">→</span></a></div></section><section class="focused-review"><div><div class="eyebrow">Your reading study plan</div><h2>James Lu + Khan Academy</h2><p>Follow the Skool Reading Comprehension and Grammar Mastery lessons with embedded Khan explanations, notes, 182 original questions, and a six-hour study route.</p></div><a class="action primary" href="https://shloksheth.github.io/james-lu-reading-writing/">Open the reading course →</a></section><section class="focused-review"><div><div class="eyebrow">Focused video practice</div><h2>The complete punctuation guide</h2><p>36 original questions: clause drills, mixed punctuation, and harder transfer. Answers include a video timestamp for review.</p></div><a class="action primary" href="#practice/lesson-25">Start punctuation practice →</a></section><div class="workspace-note"><strong>${esc(profile().name)}’s workspace</strong><p>Answers and progress stay in this browser. Use your profile menu above to switch workspaces or export a backup.</p></div>`;

 }else if(route==='course'){
 const done=COURSE.lessons.filter(complete).length;
 html=`<div class="course-layout">${courseNav()}<div><div class="eyebrow">Course overview</div><h1>James Lu SAT course</h1><p class="muted">${done} of ${COURSE.lessons.length} practice sets complete. Learn the method, practice it, and finish each unit with its section test.</p><div class="unit-overview">`;
 sections.forEach((name,i)=>{const ls=COURSE.lessons.filter(l=>l.section===i);const n=ls.filter(complete).length;html+=`<section class="unit-summary"><div class="eyebrow">Unit ${i+1}</div><h2><a href="#unit/${i}">${name}</a></h2><p>${unitDescriptions[i]}</p><div class="controls"><a class="action primary" href="#unit/${i}">Open unit →</a><span class="muted">${ls.length} lessons · ${n} complete</span></div><div class="progress" style="margin-top:20px"><div style="width:${n/ls.length*100}%"></div></div></section>`});html+='</div></div></div>';
 }else if(/^unit\/[0-3]$/.test(route)){
 const si=Number(route.split('/')[1]),ls=COURSE.lessons.filter(l=>l.section===si),done=ls.filter(complete).length;
 html=`<div class="course-layout">${courseNav(si)}<div><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="#home">Home</a> / <a href="#course">Course</a> / Unit ${si+1}</nav><div class="eyebrow">Unit ${si+1}</div><h1>${sections[si]}</h1><p class="muted">${ls.length} lessons · ${ls.reduce((n,l)=>n+l.questions.length,0)} original questions · ${done} practice sets complete</p><div class="skill-strip" aria-label="Lesson progress">${ls.map((l,i)=>`<a class="skill-mark ${complete(l)?'finished':lessonState(l)==='In progress'?'started':''}" href="#practice/${l.id}" aria-label="${esc(l.title)}: ${lessonState(l)}">${i+1}</a>`).join('')}<a class="skill-mark test-mark" href="${sectionLink(si)}" aria-label="Section test">T</a></div><p class="progress-key"><span>○ Not started</span><span>◐ In progress</span><span>● Complete</span><span>T Section test</span></p><section class="about-unit"><h2>About this unit</h2><p>${unitDescriptions[si]}</p><p class="muted">A practice set is complete after every question has been answered correctly. First-attempt results stay in each explanation, so retries do not hide what needs review.</p></section>`;
 if(si===3)html+=`<section class="focused-review"><div><h2>Your full reading study course</h2><p>Pair these James Lu videos with Khan’s dedicated skill lessons, notes, and practice. Work through all nine reading and rhetoric skills, a grammar bridge, and a separate mixed assessment.</p></div><a class="action primary" href="https://shloksheth.github.io/james-lu-reading-writing/">Open the reading plan →</a></section>`;
 let day=-1;
 ls.forEach((l,i)=>{if(day!==l.day){day=l.day;html+=`<div class="day-heading">${esc(COURSE.days[day].title)}</div>`}html+=`<section class="lesson-block"><div class="lesson-block-title"><h2>${i+1}. ${esc(l.title)}</h2><span class="tag">${lessonState(l)}</span></div><div class="learn-practice"><div><h3>Learn</h3><a class="resource-link" href="${lessonLink(l)}"><span aria-hidden="true">▷</span><span>Watch ${esc(l.title)}<small>${profile().watched[l.id]?'Marked watched':'Video lesson'}</small></span></a></div><div class="practice-panel"><h3>Practice</h3><p>${l.questions.length} original questions</p><p class="muted">${tally(l)}/${l.questions.length} correct</p><a class="action primary" href="#practice/${l.id}">${lessonState(l)==='Not started'?'Start practice':'Continue practice'} →</a></div></div></section>`});
 html+=`<section class="unit-test"><div><div class="eyebrow">Bring it together</div><h2>${sections[si]} section test</h2><p>Use the selected bank questions to review the whole unit. Scoring is provided inside the bank.</p></div><a class="action primary" href="${sectionLink(si)}">Start section test →</a></section></div></div>`;
 }else if(route==='daily'){
 html='<div class="eyebrow">Practice on your schedule</div><h1>Choose your daily set</h1><div class="grid">'+COURSE.days.map((d,i)=>`<article class="card"><h3>${esc(d.title)}</h3><p>${d.lessons.reduce((n,id)=>n+COURSE.lessons.find(l=>l.id===id).questions.length,0)} questions · ${d.lessons.length} video${d.lessons.length>1?'s':''}</p><a href="#day/${i}">Start practice →</a>${d.pdf?`<br><a href="${d.pdf}" target="_blank" rel="noopener">${[4,5].includes(i)?'Earlier 10-question PDF ↗':'PDF version ↗'}</a>`:''}</article>`).join('')+'</div>';
 }else if(route.startsWith('lesson/')||route.startsWith('day/')||route.startsWith('practice/')){
 const practiceMode=route.startsWith('practice/');const dayMode=route.startsWith('day/');const day=COURSE.days[Number(route.split('/')[1])];const lesson=COURSE.lessons.find(l=>l.id===route.split('/')[1]);
 if((dayMode&&!day)||(!dayMode&&!lesson)){location.hash='home';return}
 const ls=dayMode?day.lessons.map(id=>COURSE.lessons.find(l=>l.id===id)):[lesson];
 html=`<div class="workspace"><aside class="outline"><a href="#unit/${ls[0].section}">← Unit overview</a>`;
 COURSE.lessons.filter(l=>l.section===ls[0].section).forEach(l=>html+=`<a class="${ls.includes(l)?'active':''}" href="${lessonLink(l)}">${complete(l)?'✓ ':''}${esc(l.title)}</a>`);
 html+=`<a href="${sectionLink(ls[0].section)}">Section test →</a></aside><div><div class="eyebrow">${sections[ls[0].section]}</div><h1>${esc(dayMode?day.title:lesson.title)}</h1>`;
 ls.forEach(l=>{if(!dayMode&&!practiceMode)html+=`<iframe class="video" src="${l.embed}" title="${esc(l.title)} video lesson" allow="fullscreen" allowfullscreen></iframe><p><a href="${l.url}" target="_blank" rel="noopener">Open original lesson ↗</a> <span class="muted">· If the embed needs sign-in, use the original lesson.</span></p><button data-watch="${l.id}">${profile().watched[l.id]?'✓ Lesson marked watched':'Mark lesson watched'}</button>`;
 if(l.id==='lesson-16')html+=`<section class="focused-review"><div><h2>Flashcards &amp; punctuation practice</h2><p>34 original flashcards and 32 questions, from foundations to harder mixed problems. Study with explanations for every choice, test yourself without immediate feedback, and revisit missed questions.</p><p class="muted">This pack saves its own progress in this browser, separately from your course profile.</p></div><a class="action primary" href="lesson16-punctuation.html">Open the study pack →</a></section>`;
 html+=`${practiceMode?`<p><a href="${lessonLink(l)}">Watch the lesson →</a> · <a href="#unit/${l.section}">Unit overview</a></p>`:''}${l.practiceIntro?`<section class="about-unit"><h2>How to use this set</h2><p>${esc(l.practiceIntro)}</p><details><summary>Rules to check</summary><p>${esc(l.studyGuide)}</p></details></section>`:''}${l.coverage?coverageHTML(l):''}${l.regressionGuide?`<details class="regression-guide"><summary>How to enter these regressions</summary><p>${esc(l.regressionGuide)}</p><p>Use the Copy buttons in an answer explanation to paste a line into Desmos with its math formatting. Copy one line at a time. If typing a restriction manually, use the calculator’s brace keys.</p></details>`:''}${l.visualWalkthroughs?regressionGalleryHTML(l):''}<div class="hard-banner"><strong>${l.practiceIntro?'Punctuation practice':l.coverage?'Regression practice':'Hard-mode calibration'}</strong><span>${esc(l.questions[0]?.hardFocus||'Multi-step reasoning with SAT-style distractors')}</span></div><h2>${dayMode?esc(l.title):'Put it into practice'}</h2><p class="muted">${tally(l)}/${l.questions.length} correct · Submit an answer to see its explanation. Numeric answers accept decimals or fractions.</p>`;
 l.questions.forEach((q,i)=>html+=questionHTML(q,i));
 const next=COURSE.lessons[COURSE.lessons.indexOf(l)+1];
 html+=`<div class="banner"><strong>${complete(l)?'Practice mastered. Ready for the next step.':'Keep going — review missed questions and try them again.'}</strong><div class="controls" style="margin-top:14px"><button data-retry="${l.id}">Retry missed questions</button><button class="reset-control" data-reset-lesson="${l.id}" ${l.questions.some(q=>profile().answers[q.id])?'':'disabled'}>Reset this practice set and its attempt history</button><a class="action primary" href="${next&&next.section===l.section?lessonLink(next):sectionLink(l.section)}">${next&&next.section===l.section?'Next lesson':'Section test'} →</a></div></div>`;
 });html+='</div></div>';
 }else{location.hash='home';return}
 $('#content').innerHTML=html+resetStatusHTML();
 document.querySelectorAll('form[data-question]').forEach(f=>f.onsubmit=e=>{e.preventDefault();const q=COURSE.lessons.flatMap(l=>l.questions).find(q=>q.id===f.dataset.question);const val=new FormData(f).get('answer');if(!val||!String(val).trim())return;const prev=profile().answers[q.id];const correct=q.choices?val===q.answer:numericEqual(val,q.answer);profile().answers[q.id]={value:val,correct,firstCorrect:prev?.firstCorrect??correct,attempts:(prev?.attempts||0)+1,submitted:true};markAnswerChanged(store.active,q.id);resetMessage='';save();saveResetUndo();const y=scrollY;render();window.scrollTo(0,y)});
 document.querySelectorAll('[data-reset-question]').forEach(b=>b.onclick=()=>resetSavedAnswers([b.dataset.resetQuestion],'Question'));
 document.querySelectorAll('[data-reset-lesson]').forEach(b=>b.onclick=()=>{const lesson=COURSE.lessons.find(l=>l.id===b.dataset.resetLesson);if(lesson)resetSavedAnswers(lesson.questions.map(q=>q.id),lesson.title)});
 document.querySelectorAll('[data-undo-reset]').forEach(b=>b.onclick=undoLastReset);
 document.querySelectorAll('[data-dismiss-reset]').forEach(b=>b.onclick=()=>{resetMessage='';render()});
 document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{const target=document.getElementById(b.dataset.jump);target?.scrollIntoView({behavior:'smooth',block:'start'});target?.querySelector('input')?.focus({preventScroll:true})});
 document.querySelectorAll('[data-watch]').forEach(b=>b.onclick=()=>{profile().watched[b.dataset.watch]=!profile().watched[b.dataset.watch];save();render()});
 document.querySelectorAll('[data-copy-question]').forEach(b=>b.onclick=async()=>{const q=COURSE.lessons.flatMap(l=>l.questions).find(q=>q.id===b.dataset.copyQuestion);const m=q?.regressionSteps;const line=(m?.pasteEntries||m?.entries)?.[Number(b.dataset.copyLine)];if(!line)return;const status=b.closest('.desmos-method').querySelector('.copy-status');try{await navigator.clipboard.writeText(line);status.textContent=`Line ${Number(b.dataset.copyLine)+1} copied. Paste into a fresh Desmos expression.`}catch{status.textContent='Copy is unavailable in this browser. Type the line above into Desmos.'}});
 document.querySelectorAll('[data-retry]').forEach(b=>b.onclick=()=>{const l=COURSE.lessons.find(l=>l.id===b.dataset.retry);l.questions.forEach(q=>{const a=profile().answers[q.id];if(a&&!a.correct){a.submitted=false;markAnswerChanged(store.active,q.id)}});resetMessage='';save();saveResetUndo();render();const first=l.questions.find(q=>profile().answers[q.id]&&!profile().answers[q.id].correct);if(first)document.getElementById(first.id)?.scrollIntoView({behavior:'smooth',block:'center'})});
}
function numericValue(raw){const s=String(raw).trim().replace(/−/g,'-').replace(/,/g,'');if(/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)\s*\/\s*[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(s)){const [a,b]=s.split('/').map(Number);return b===0?NaN:a/b}return /^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(s)?Number(s):NaN}
function numericEqual(a,b){const x=numericValue(a),y=numericValue(b);return Number.isFinite(x)&&Number.isFinite(y)&&Math.abs(x-y)<=1e-6*Math.max(1,Math.abs(y))}
function coverageHTML(l){return `<details class="coverage"><summary>Coverage check · ${l.questions.length} skills · ${tally(l)} correct</summary><p>${esc(l.coverageNote)}</p><ol>${l.questions.map((q,i)=>`<li><button data-jump="${q.id}"><span class="coverage-number">${i+1}.</span><span>${esc(q.topic)}</span><span class="coverage-state">${profile().answers[q.id]?.correct?'✓ Correct':profile().answers[q.id]?'Review':'Not tried'}</span></button></li>`).join('')}</ol></details>`}
function regressionFigureHTML(v){return `<figure class="regression-visual"><a href="${esc(v.image)}" target="_blank" rel="noopener" aria-label="Open full-size Desmos screenshot: ${esc(v.title)}"><img src="${esc(v.image)}" alt="${esc(v.alt)}" loading="lazy" width="1360" height="950"></a><figcaption><strong>Actual SAT calculator screenshot.</strong> ${esc(v.caption)} <a href="${esc(v.image)}" target="_blank" rel="noopener">Open full size ↗</a></figcaption></figure>`}
function regressionGalleryHTML(l){return `<details class="regression-gallery"><summary>Visual walkthroughs · ${l.visualWalkthroughs.length} worked examples</summary><p class="muted">These show answers. Try the related questions first, then compare your calculator with the screenshots.</p>${l.visualWalkthroughs.map(id=>{const q=l.questions.find(q=>q.id===id),v=q.regressionSteps.visual;return `<details class="visual-example"><summary>${esc(v.title)} · Question ${l.questions.indexOf(q)+1}</summary>${regressionFigureHTML(v)}<button data-jump="${q.id}">Go to this question →</button></details>`}).join('')}</details>`}
function regressionHTML(q){const m=q.regressionSteps;return `<section class="desmos-method" aria-label="Desmos regression explanation"><h3>Desmos regression method</h3><p><strong>1. Set up the unknowns.</strong> ${esc(m.setup)}</p><p><strong>2. Enter each line separately.</strong> Start in a fresh graph for this question. Use Copy to preserve the math formatting when pasting.</p><div class="regression-entries">${m.entries.map((line,i)=>`<div><span>Line ${i+1}</span><code>${esc(line)}</code><button data-copy-question="${esc(q.id)}" data-copy-line="${i}" aria-label="Copy line ${i+1} for Desmos">Copy</button></div>`).join('')}</div><p class="copy-status muted" role="status" aria-live="polite"></p><p><strong>3. Read the result and verify.</strong> ${esc(m.check)}</p>${m.visual?`<details class="visual-example"><summary>See this question in Desmos</summary>${regressionFigureHTML(m.visual)}</details>`:''}</section>`}
function questionHTML(q,i){const a=profile().answers[q.id];const locked=a?.submitted;let h=`<article class="question" id="${q.id}"><div class="question-meta"><div class="eyebrow">Question ${i+1}</div><span class="difficulty-badge">${esc(q.difficulty||'Hard')}</span></div>${q.topic?`<p class="question-topic">${esc(q.topic)}</p>`:''}<p class="stem">${rich(q.stem)}</p>`;
 h+=(q.equations||[]).map(src=>`<img class="equation" src="${src}" alt="${esc(q.math)}">`).join('');
 if(q.image)h+=`<img class="figure" src="${q.image}" alt="${esc(q.imageAlt||'Diagram for this question')}">`;
 if(q.figure?.type==='table')h+='<table><thead><tr>'+q.figure.headers.map(x=>'<th scope="col">'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+q.figure.rows.map(row=>'<tr>'+row.map(x=>'<td>'+esc(x)+'</td>').join('')+'</tr>').join('')+'</tbody></table>';
 h+=`<form data-question="${q.id}"><fieldset style="border:0;padding:0;margin:0" ${locked?'disabled':''}><legend class="muted">Your answer</legend>`;
 if(q.choices)q.choices.forEach((c,j)=>{const v=String.fromCharCode(65+j);h+=`<label class="choice"><input type="radio" name="answer" value="${v}" required ${a?.value===v?'checked':''}><span><strong>${v}.</strong> ${rich(c)}</span></label>`});
 else h+=`<label><input class="numeric" name="answer" aria-label="Answer for question ${i+1}" value="${esc(a?.value||'')}" placeholder="e.g. 0.5 or 1/2" required inputmode="text"></label>`;
 h+=`<button class="primary" style="margin-top:14px">Check answer</button></fieldset></form><div class="question-reset"><button class="reset-control" data-reset-question="${esc(q.id)}" ${a?'':'disabled'}>Reset question and its attempt history</button></div>`;
 if(locked)h+=`<div class="feedback ${a.correct?'':'wrong'}" role="status"><strong>${a.correct?'Correct':'Keep reviewing'} · Answer: ${esc(q.answer)}</strong><p>${rich(q.why)}</p>${q.reviewUrl?`<p class="review-link"><strong>Review: ${esc(q.skill)}</strong><br><a href="${esc(q.reviewUrl)}" target="_blank" rel="noopener">Rewatch the related video segment ↗</a></p>`:''}${q.regressionSteps?regressionHTML(q):q.desmos?`<p class="desmos-method"><strong>Desmos method</strong><br>${esc(q.desmos)}</p>`:''}<p class="muted">First attempt: ${a.firstCorrect?'correct':'missed'} · ${a.attempts} attempt${a.attempts===1?'':'s'}</p></div>`;
 return h+'</article>';
}
function profileMenu(){const s=$('#profile-select');s.replaceChildren(...Object.entries(store.profiles).map(([id,p])=>{const o=document.createElement('option');o.value=id;o.textContent=p.name;return o}));s.value=store.active}
$('#profile-button').onclick=()=>{profileMenu();$('#profiles').showModal()};$('#close-profile').onclick=()=>$('#profiles').close();
$('#profile-select').onchange=e=>{store.active=e.target.value;save();render()};
$('#new-profile').onsubmit=e=>{e.preventDefault();const name=$('#profile-name').value.trim();if(!name)return;const id=crypto.randomUUID();store.profiles[id]={name,answers:{},watched:{}};store.active=id;save();profileMenu();render();$('#profile-name').value='';$('#profile-status').textContent='Profile created on this device.'};
$('#export').onclick=()=>{const blob=new Blob([JSON.stringify({format:'jl-sat-backup-v1',profile:profile()},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='sat-practice-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('#import').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>2000000)throw Error();const imported=importPracticeProfile(JSON.parse(await f.text()));const id=crypto.randomUUID();store.profiles[id]=imported;store.active=id;save();profileMenu();render();$('#profile-status').textContent='Backup imported as a new profile.'}catch{$('#profile-status').textContent='Could not import this file. Choose a SAT practice backup.'}e.target.value=''};
window.addEventListener('storage',e=>{if(e.key!==key||!e.newValue)return;try{const s=JSON.parse(e.newValue);if(s?.profiles?.[s.active]){store=s;resetUndo={revision:0,revisions:{},actions:[]};resetMessage='';saveResetUndo();render()}}catch{}});
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0)});save();render();
